version: '3.5'
services:
  worker:
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile.dev
    command: ["npm", "--prefix", "packages/worker", "run", "dev"]
    env_file:
      - .development.env
    ports:
      - 5001:5001
  user:
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile.dev
    command: ["npm", "--prefix", "packages/user", "run", "dev"]
    env_file:
      - .development.env
    ports:
      - 4001:4001
  cassandra-web:
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile.dev
    command: ["npm", "--prefix", "packages/cassandra-web", "run", "dev"]
    env_file:
      - .development.env
    ports:
      - 1001:1001