version: '3.5'
services:
  worker:
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile
    env_file:
      - .production.env
    ports:
      - 5000:5000
  user:
    build:
      context: .
      dockerfile: ./docker/user/Dockerfile
    env_file:
      - .production.env
    ports:
      - 4000:4000
  cassandra-web:
    build:
      context: .
      dockerfile: ./docker/cassandra-web/Dockerfile
    env_file:
      - .production.env
    ports:
      - 1000:1000